<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChangFu.Domain\ChangFu.Domain.csproj" />
    <ProjectReference Include="..\ChangFu.FutuAdapter\ChangFu.FutuAdapter.csproj" />
  </ItemGroup>
</Project>
